project_id = "hcbkqygdtzpxvctfdqbd"

[functions.appypay-token]
verify_jwt = false

[functions.appyay-create-charge]
verify_jwt = false

[functions.checkout-prerender]
verify_jwt = false

[functions.kambapay-public-api]
verify_jwt = false

[functions.member-area-login]
verify_jwt = false

[functions.member-area-verify]
verify_jwt = false

[functions.member-area-logout]
verify_jwt = false
