project_id = "hcbkqygdtzpxvctfdqbd"

[functions.bunny-video-upload]
verify_jwt = false

[functions.checkout-prerender]
verify_jwt = false

[functions.create-appypay-charge]
verify_jwt = false

[functions.kambapay-public-api]
verify_jwt = false

[functions.member-area-login]
verify_jwt = false

[functions.member-area-verify]
verify_jwt = false

[functions.member-area-logout]
verify_jwt = false

[functions.member-area-custom-login]
verify_jwt = false

[functions.custom-auth-login]
verify_jwt = false

[functions.update-order-status]
verify_jwt = false

[functions.create-multibanco-order]
verify_jwt = false

[functions.send-sms-notification]
verify_jwt = false

[functions.appypay-webhook]
verify_jwt = false