project_id = "hcbkqygdtzpxvctfdqbd"

[functions.bunny-video-upload]
verify_jwt = false

[functions.checkout-prerender]
verify_jwt = false

[functions.create-appypay-charge]
verify_jwt = false

[functions.create-stripe-checkout-session]
verify_jwt = false

[functions.kambapay-public-api]
verify_jwt = false

[functions.member-area-login]
verify_jwt = false

[functions.member-area-verify]
verify_jwt = false

[functions.member-area-logout]
verify_jwt = false

[functions.member-area-custom-login]
verify_jwt = false

[functions.custom-auth-login]
verify_jwt = false

[functions.update-order-status]
verify_jwt = false

[functions.create-multibanco-order]
verify_jwt = false

[functions.send-sms-notification]
verify_jwt = false

[functions.appypay-webhook]
verify_jwt = false

[functions.marca-milionaria-webhook]
verify_jwt = false

[functions.ia-lucrativo-webhook]
verify_jwt = false

[functions.add-member-area-student]
verify_jwt = false

[functions.bulk-register-ia-lucrativo]
verify_jwt = false

[functions.member-area-reset-password]
verify_jwt = false

[functions.verify-signup-code]
verify_jwt = false

[functions.send-2fa-code]
verify_jwt = false

[functions.verify-2fa-code]
verify_jwt = false